name: exnote
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  intl: ^0.20.2
  path: ^1.9.1
  provider: ^6.1.5+1
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png" # Path to your image file